---
title: "Literature Review"
subtitle: "Co-policing Surrounding the University of Chicago"
author: "Adam Shelton"
date: "11/22/2019"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
bibliography: sources.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--
## Research Questions

While the UCPD provides significant technical and human resources to police Hyde Park and the surrounding area, their jurisdiction is shared with the Chicago Police Department (CPD). This necessitates an understanding, not only of how the UCPD operates, but also of the CPD and the interaction of private police officers employed by the University with public police officers employed by the city. Therefore, in addition to understanding the reports of crimes that UCPD receives and responds to, and their outcomes, this project must answer how CPD crime reports and outcomes vary within the UCPD's jurisdiction, and directly outside of it. As some reports of crimes are handled by both the UCPD and CPD in tandem, we can also directly discern departmental in differences in how each agency may handle or report the same "case" in a different manner. 

We would expect that the UCPD handles fewer violent crimes and processes less arrests than CPD over the same time period. It is likely the reports of crimes and responses to crimes by the UCPD escalate during the school years, with less activity during summer break. Certain types of crimes, like sexual crimes or thefts are more likely to be handled by UCPD. 

It would appear likely that issues in inequitable policing would be relatively consistent between departments. Officers in both agencies are the results of similar training pipelines, with UCPD officers training with CPD officers [@Heaton2016; @Sherman2019]. While racial bias has been discovered in the UCPD's policing efforts [@Newman2016], they also take additional training courses beyond what the CPD provides [@Heaton2016], which should reduce bias in policing. 

With these two police forces in such close proximity, it is important that their actions and interactions be compared to determine equitability across the spectrum of policing in the Hyde Park area. Police officers can exercise a significant amount of discretion when stopping a civilian, which is likely to be shaped by institutional forces. Identifying irregularities in the UCPD's habits, which may allude to these institutional forces and the stakeholders interests they reflect, necessitates a comparison to a "baseline", in this case the CPD.  
-->

## Inequality in Policing

Since the 1970's, mass incarceration produced by an increase in punitive policing, such as the War on Drugs, have been used to perpetuate racial injustices, with "African Americans are incarcerated at nearly six times the rate of whites, and Hispanics are incarcerated at almost twice the rate of whites" [@Fortner2015]. America still lives in segregated communities, leading to separated communities of color exhibiting higher crime rates, not due to residents but the lack of jobs, education, and other opportunities [@Capers2009]. The absence of social capital "...that can increase the likelihood of upward mobility is likely to be self-perpetuating..." [@Capers2009]. This leads to higher unemployment and lower property values in minority neighborhoods, which coupled with decreased trust and perceived legitimacy of police officers, can exacerbate issues of crime and policing in these communities [@Capers2009]. 

This creates serious consequences for all people, but especially affects those in society that are already disadvantaged. There is a long history of public policing being racialized or otherwise not applied equally across the population [@Alpert2006; @Tuch1997]. Communities of color have been consistently more likely to be subjected to excessive force, exacerbating inequality through social ramifications, like distrust for police and authority [@Tuch1997]. Residents in black neighborhoods are also more likely to say that "police stop people in the neighborhood without good reason, verbally abuse neighborhood residents, and and use excessive force against neighborhood residents" [@Weitzer2000]. These problems exist in public police departments across the country, but often goes unaddressed, as white people are less likely to think racism in policing exists [@Tuch1997; @Weitzer2000]. Yet, in many areas, white officers make up a greater proportion of the police force [@Tuch1997] and are more likely to give out tickets [@Alpert2006]. Due to high levels of racial segregation, white police officers are likely to come from predominately white neighborhoods, while predominately interacting with people of color only on patrol, which can reinforce stereotypes and racialized policing [@Capers2009].

Gentrification, while reducing the intensity of policing in the immediate area, can increase policing activity outside of the gentrifying area [@Laniyonu2018]. However, despite a decrease in policing, it appears crime actually increases in gentrifying areas [@Laniyonu2018]. While Broken Windows policing, which focused on reducing physical disorder in an attempt to reduce crime, was very popular during the 1980's and 1990's, there is contradictory evidence about its effectiveness [@Laniyonu2018]. Likely due to the stereotypical associations of people of color and poor with crime, there is strong evidence that the proportion of black Americans in an area is correlated with the distribution of police officers [@Laniyonu2018; @Capers2009]

Typically the decision-making by police officers leading up to a stop is driven by a person appearing "different" or "out of place" [@Alpert2006]. As a result, minorities are frequently stopped in white neighborhoods, despite data showing that police suspicions about criminality in most stop and frisks are wrong [@Capers2009]. Policing guided by these philosophies invites bias into the policing process, resulting in the targeting of males and minorities [@Alpert2006]. Policing that does not adequately address the concerns of the community, expectedly can have as detrimental effects on the community as crime can [@Daniel1970]. While crime drives down patronage of businesses, churches, and community organizations, that communities of color revolve around, ineffective policing only increases feelings of danger in the community [@Daniel1970]. Policies that emphasize transparency and accountability in policing to the community are not only comforting to residents, but result in more effective enforcement of laws.

## Private Policing

Private policing is a large and growing industry, with companies spending approximately $30 billion in 2015 on private security [@Pappas2012]. The United States Department of Labor estimated that in 2018 1.15 million people in the United States were employed as Security Guards or Gaming Surveillance Officers [@USDepartmentofLabor2018]. Guarding represents approximately half of all private security services, with 35 percent of services utilizing armed guards [@Strom2010]. Retail, restaurants, and food service was the industry sector with the highest percentage of security officers per employees in 2009 at about 17 percent [@Strom2010]. Colleges and universities were ranked tenth with a four percent ratio of security officers to employees [@Strom2010]. The State of Illinois requires that any private detective, private security contractor, private alarm contractor, fingerprint vendor, or locksmith be licensed by the state [@225ILCS4472004]. However, it is likely for these measurements to be *underestimates* of the size of private policing [@Sklansky2011]. Quantitatively measuring the scope of private police is incredibly difficult, due to the secrecy and ambiguity surrounding the number of employees performing security work [@Sparrow2014; @Sklansky2011].

With private police these issues with accountability and representativeness become even more difficult to address, especially as they have become a more integral part of society. In the United States, there has been considerable growth in private policing in the last half century, sparking questions about the motivations of these private forces [@Shearing1992]. It is now common for public and private police departments to collaborate within their jurisdictions [@Shearing1992; @Sparrow2014], effectively creating a "network of public police and private security that is often overlapping, complimentary [sic] and mutually supportive" [@Bouthillier2006]. As governments have sought to cut costs, and private organizations have seen it more cost effective to hire their own workforce for protection, there has been a shift in social control out of the public sphere [@Shearing1992; @Joh2006]. 

Americans quickly became disillusioned of private policing in the early years of the mining and railroad industries. Private police forces used by the companies in these industries lead to a protection of assets over employees and went against the public interest [@Spitzer2011; @Joh2006]. This resulted in a long period where the state held a "monopoly" on policing. However, starting in the 1960's private policing began to expand, partly in response to a RAND report that re-framed private policing as "an 'industry' providing a 'service'" [@Shearing1992; @Joh2006].

Supporters of this expansion of private police forces claimed that public police had not been provided enough resources to adequately patrol their jurisdictions, creating this "vacuum" which private police were filling. This was framed as a win for everyone, as private police were now performing a role which taxpayers needed but also did not have to fund, and regulations would limit their power [@Shearing1992; @Joh2006]. Critics were concerned that now companies could give employees "state authority", and that this cooperation between governments and corporations would only protect the interests of the elite [@Shearing1992]. 

In recent history, private policing within corporations has shifted to focus on investigative labor [@Spitzer2011]. This shift represents a growing emphasis on obtaining "restitution" versus "revenge" [@Spitzer2011]. Thorough investigations allow for a better likelihood of restitution through legal means, while minimizing the risk of valuable information becoming public [@Spitzer2011]. However, any company's goal is to maximize profits, which means occasionally relying on public police, as that incurs no costs to the company [@Spitzer2011].

Privatized police officers are particularly problematic when it comes to accountability, as there is a much lower legal standard for how private forces should operate. Private police forces are now under much less government scrutiny, as public police departments rely on the partnership they have with private forces [@Joh2006]. Citizens also have fewer legal protections from private police, who are not under any constitutional obligation to follow due process regulations [@Sklansky1999]. This means that private police forces are not obligated to provide Miranda warnings before interrogation, and evidence discovered by a search is almost always admissible, although the officer could be charged with assault, trespassing, or false imprisonment [@Sklansky1999]. 

Yet, despite this lack of regulation, private police officers often have the same or similar powers of public police, over that of which other citizens have [@Sklansky1999]. Additionally, private police forces formed by companies are oftentimes allowed to sit in on regional or federal task forces, giving companies access to sensitive information they did not have before [@Joh2006]. 

This creates far-reaching implications, especially in the case of university police forces, where private police patrol large areas outside of the campus. When these officers have the power to police citizens other than students, there is little to no oversight on whether this power is being exercised fairly and justly, which is antithetical to the strict limitations imposed on police in the Constitution. There will always be instances where the interests of private police are against that of the public's [@Sparrow2014]. It is important that citizens understand when these private forces are acting against the public's interests, not only to help protect themselves, but to also spread awareness for this alarming status quo, motivating law makers to more heavily regulate private police forces. 

## Campus Policing

Approximately two-thirds of four year colleges or universities with more than 2,500 students employ sworn police officers, with 92 percent of public institutions and 38 percent of private institutions doing so [@Reaves2015]. About three quarters of campus officers overall are armed and about eight in ten campus officers could arrest and patrol beyond campus boundaries [@Reaves2015]. A larger proportion of police departments at public institutions met regularly with advocacy groups than private institutions [@Reaves2015]. The increase in law enforcement personnel has outpaced student enrollment [@Reaves2015]. Campuses with sworn officers, on average employed 2.4 full time sworn officers per 1000 students, with private institutions having higher ratios than public institutions [@Reaves2015].

Under the Jeanne Clery Disclosure of Campus Security Policy and Campus Crime Statistics Act of 1990, institutions of higher education that participate in federal financial aid programs must keep and disclose information about crime on and around campus [@Reaves2015; @Bauman2014]. On average, overall crime rates are higher at private institutions, both both public and private institutions reported handling about 40 violent crimes per 100,000 students during the 2011-2012 school year [@Reaves2015]. Usually, "sworn officers must undergo a considerably more rigorous screening process prior to hiring than their non-sworn counterparts", but a majority of departments require a college degree for both types of officer [@Reaves2015]. While the proportion of minority officers and female officers increased from the previous survey in 2004, the majority of sworn officers were both white and male during the 2011-2012 school year [@Reaves2015].

In some ways, campus police can better serve the public's interests than public police departments. While campus police work to maintain a "good image" of the school by enforcing campus rules for students [@Jacobsen2015], they can still benefit the public, sometimes more effectively than municipal police departments. Overall, campus police feel their job is to keep students safe and make them feel comfortable [@Williams2016]. Police officers employed by universities must undergo Title IX training as all university employees must, and often complete more training about sexual harassment than their municipal counterparts [@Smith2016]. Officers with specialized training pertaining to sexual crimes typically scored lower on scales of rape myth acceptance [@Smith2016]. Perhaps a testament to this focus on safety by campus police, students generally regard their campus as a "protected space" which is safer than other areas and feel that campus police are responsible for this safe environment [@Williams2016; @Jacobsen2015]. 

Yet, while in a 1998 survey of white college students and faculty only ten percent of respondents felt unsafe on their campus, 36 percent supported arming campus police officers and an additional 26 percent were undecided [@Hummer1998]. Of the 38 percent of respondents that felt campus police should not be armed, "50 percent felt
that "campus life" is not that life-threatening and therefore did not warrant the carrying of firearms by officers" [@Hummer1998]. 63 percent of respondents who were undecided felt that "the use of firearms should be dependent on the severity of the situation" [@Hummer1998].

Campus police officers also play different roles in the lives of those within their jurisdiction. Police on campuses often must play the role of a more parental figure, as most young adults at college are growing into and adjusting to their first experiences living on their own [@Williams2016]. Students feel that campus police officers should protect them while simultaneously not interfering with their lives, such as "overreacting" to students participating in under-aged drinking [@Jacobsen2015]. This puts campus police officers in an interesting situation, where they are thought of by many students to be "not real cops", while oftentimes still having the same legal powers as public law enforcement officers [@Williams2016]. Students also delegitamize campus police by popularizing rumors that campus police are officers that could not get a job with the state or municipal police [@Jacobsen2015] or anecdotes of excessive force [@Williams2016]. 

This lack of legitimacy of campus police in students' eyes may also stem from the history of campus police. Early campus police in the first half of the twentieth century were little more than security guards, who could investigate and detain, but only refer to the administration for punishment [@Sloan1992]. As unrest became widespread on campuses across the country in the late 1960's, college administrators faced losing control of their student populations, and a reliance on outsiders to keep peace on campus [@Sloan1992]. Colleges were also growing rapidly during this time, which was accompanied by increases in crime [@Sloan1992]. This led to the founding of official campus police departments made up of sworn law enforcers whose training, duties, and organization mirrored that of traditional urban police departments [@Sloan1992].  

However, the attitudes of university police officers greatly contrast that of students attending the university. Overwhelmingly, campus police felt that students were, in general, respectful of the rules and cooperative with officers [@Sloan1992]. Officers felt that while a minority of students created most of the trouble, outsiders posed the greatest threat to campus security [@Sloan1992]. Campus police felt a strong sense of duty towards serving the university community and enforcing campus rules [@Gelber1972]. This gives evidence that while campus police officers must police a much different population with different types of crimes than municipal police traditionally do, that they will react and operate in a similar manner. 

This commitment to serving is also portrayed through campus police departments' interaction with the community at large. Campus police departments are slightly more likely to have a community policing plan, either written or not, and provide at least eight hours of community police training, when compared to city police [@Bromley2003]. Campus and city police departments have roughly the same proportion of full time community police officers, about seven in ten [@Bromley2003]. While campus police forces are more likely to have problem solving partnerships with citizens, city departments are more likely to have trained citizens in problem solving [@Bromley2003]. Campus officers are overwhelmingly more likely to be assigned to foot or bike patrols than city police officers [@Bromley2003].

Traditionally, while public universities are considered an extension of the state, private universities are not considered state actors, even when university police forces are involved [@Jahnig2015]. The Supreme Court of North Carolina determined that religious colleges do not violate the Establishment Clause, which designates the separation of religious institutions and the law, as long police officers from religious colleges are enforcing the laws of the state, and therefore not advancing one religion through their actions [@Hopkins2014]. However, the Ohio Supreme Court ruled in May 2015 that the police department of Otterbein University, a private institution, was a public office that can be compelled to release records as "its officers are sworn, state-certified police officers who exercise plenary police power", which goes against the traditional legal precedent in this regard [@142OhioSt.3d5352015]. 

Under the federal 1033 program, municipal police departments, including departments operated by universities can receive military surplus for only the cost of shipping and receiving [@Bauman2014]. At least 124 colleges have received equipment through this program, ranging from outer-wear to assault rifles, grenade launchers and armored vehicles [@Bauman2014]. Campus police personnel claim these are only for "serious incidents", but critics argue the equipment is unnecessary and concerning, especially in the wake of incidents of police brutality, like those that occurred in Ferguson [@Bauman2014]. While departments must show proof that officers have received training to use any new weapon, vehicle, or tool to maintain accreditation from the International Association of Campus Law Enforcement Administrators, there is no requirement for campus police departments to attain accreditation [@Bauman2014].

Institutions of higher education cannot create their own police departments without some kind of state authorization [@Hopkins2014]. At least 44 states have authorized campus policing, but the method and the degree to which these policing powers are vested to universities and colleges varies greatly by state, with some states granting full policing powers to campus officers, while others force campuses to have their officers deputized by municipal departments [@Hopkins2014]. In Illinois, the Private College Campus Police Act gives private colleges and universities the power to appoint members of a campus police department with "...the powers of municipal peace officers and county sheriffs, including the power to make arrests...for violations of state statutes or municipal or county ordinances, including the ability to regulate and control traffic on the public way contiguous to the college or university property...in the county where the college or university is located" [@110ILCS1020]. 

## The University of Chicago

The University of Chicago Police Department (UCPD) is the largest private police force in Chicago [@Reaves2008], encompassing a jurisdiction of approximately 6.5 miles and 65,000 people [@Larson2012]. The University of Chicago had the twelfth largest campus police force by number of full time employees in the country during the 2011-2012 school year [@BureauofJusticeStatistics2015]. UCPD officers, like those on many other campuses across the United States, are fully accredited, armed, and sworn [@Heaton2016] and authorized to operate throughout all of Cook County [@Sherman2019]. The UCPD patrols Hyde Park and five surrounding neighborhoods, sharing the area with Chicago Police patrols [@Sherman2019]. 

The University of Chicago has a rich history of using the policing of "things", through urban renewal policies, and the policing of people to further their own agenda [@Sherman2019; @Larson2012]. The university created their own police department in the 1960's in response to parents' concern about the safety of their children, and the administration's concern about enrollment [@Sherman2019; @Larson2012]. While the university started by convincing the Chicago police commissioner to deputize their officers, an Illinois law passed in 1989 gave universities the power to swear in their own police officers [@Sherman2019; @Larson2012]. 

Racial tensions surrounding the UCPD have persisted to this day. Students of color attending The University of Chicago have reported carrying a backpack and frequently wearing UChicago branded clothing to avoid being hassled by UCPD [@Honig2014; @Gold2014]. A bill in introduced by a representative for the Hyde Park area in the Illinois General Assembly requiring universities to release information died in committee after the University of Chicago promised to release policing data [@Newman2015]. In response to community outcries about racial profiling and transparency, the University agreed to publicly release information on the UCPD and their interactions with civilians in 2015, despite having no legal obligation to do so [@TheUniversityofChicago2015; @Newman2016]. However, the released data does not appear to clear the UCPD of racial bias, as "African-Americans make up approximately 59 percent of the population in UCPD’s patrol area but 93 percent of UCPD’s field interviews" [@Newman2016]. These well-documented systematic issues within the UCPD warrant additional research to better equip activists and policy makers seeking to make policing in the surrounding community more equitable and in the interest of the public.

Modern campuses, have spread beyond buildings owned by the university, to residences and businesses that students frequent, necessitating extended jurisdictions beyond campus [@Hopkins2014]. While the Chicago Police Department has entered into jurisdiction agreements with the University of Chicago Police Department and Northwestern University Police Department, whereas those agencies generally patrol defined geographical areas, the CPD still retains the authority to provide "all required police services" in these jurisdictions [@ChicagoPoliceDepartment2017].

\newpage
## References
