---
title: "Thesis Proposal"
subtitle: "Co-policing Surrounding the University of Chicago"
author: "Adam Shelton"
date: "11/15/2019"
header-includes:
    - \usepackage{setspace}\doublespacing
output: pdf_document
bibliography: sources.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--
I am studying policing surrounding UChicago
  because I want to know how and why UCPD and CPD interact and react differently to crimes in the Hyde Park area
    in order to better educate students and citizens on how public and private policing work together to affect their lives
-->   

## Introduction

The University of Chicago Police Department (UCPD) is the largest private police force in Chicago [@Reaves2008], encompassing a jurisdiction of approximately 6.5 miles and 65,000 people [@Larson2012]. UCPD officers, like those on many other campuses across the United States, are fully accredited, armed, and sworn [@Heaton2016] and authorized to operate throughout all of Cook County [@Sherman2019]. The UCPD patrols Hyde Park and five surrounding neighborhoods, sharing the area with Chicago Police patrols [@Sherman2019]. 

The University of Chicago has a rich history of using the policing of "things", through urban renewal policies, and the policing of people to further their own agenda [@Sherman2019; @Larson2012]. The university created their own police department in the 1960's in response to parents' concern about the safety of their children, and the administration's concern about enrollment [@Sherman2019; @Larson2012]. While the university started by convincing the Chicago police commissioner to deputize their officers, an Illinois law passed in 1989 gave universities the power to swear in their own police officers [@Sherman2019; @Larson2012]. 

Racial tensions surrounding the UCPD have persisted to this day. Students of color attending The University of Chicago have reported carrying a backpack and frequently wearing UChicago branded clothing to avoid being hassled by UCPD [@Honig2014; @Gold2014]. In response to community outcries about racial profiling and transparency, the University agreed to publicly release information on the UCPD and their interactions with civilians in 2015 [@TheUniversityofChicago2015; @Newman2016]. However, the released data does not appear to clear the UCPD of racial bias, as "African-Americans make up approximately 59 percent of the population in UCPD’s patrol area but 93 percent of UCPD’s field interviews" [@Newman2016]. These well-documented systematic issues within the UCPD warrant additional research to better equip activists and policy makers seeking to make policing in the surrounding community more equitable and in the interest of the public.

## Research Questions

While the UCPD provides significant technical and human resources to police Hyde Park and the surrounding area, their jurisdiction is shared with the Chicago Police Department (CPD). This necessitates an understanding, not only of how the UCPD operates, but also of the CPD and the interaction of private police officers employed by the University with public police officers employed by the city. Therefore, in addition to understanding the reports of crimes that UCPD receives and responds to, and their outcomes, this project must answer how CPD crime reports and outcomes vary within the UCPD's jurisdiction, and directly outside of it. As some reports of crimes are handled by both the UCPD and CPD in tandem, we can also directly discern departmental in differences in how each agency may handle or report the same "case" in a different manner. 

We would expect that the UCPD handles fewer violent crimes and processes less arrests than CPD over the same time period. It is likely the reports of crimes and responses to crimes by the UCPD escalate during the school years, with less activity during summer break. Certain types of crimes, like sexual crimes or thefts are more likely to be handled by UCPD. 

It would appear likely that issues in inequitable policing would be relatively consistent between departments. Officers in both agencies are the results of similar training pipelines, with UCPD officers training with CPD officers [@Heaton2016; @Sherman2019]. While racial bias has been discovered in the UCPD's policing efforts [@Newman2016], they also take additional training courses beyond what the CPD provides [@Heaton2016], which should reduce bias in policing. 

With these two police forces in such close proximity, it is important that their actions and interactions be compared to determine equitability across the spectrum of policing in the Hyde Park area. Police officers can exercise a significant amount of discretion when stopping a civilian, which is likely to be shaped by institutional forces. Identifying irregularities in the UCPD's habits, which may allude to these institutional forces and the stakeholders interests they reflect, necessitates a comparison to a "baseline", in this case the CPD.  

## Significance

Lives can be preserved or broken at the whim of law enforcement officers. Everyday, each of us are affected by the policing around us, both public and private, even if we never interact with an officer. The policies that drive public policing are considerably more translucent and malleable than those that control private policing, making it even more essential that the interactions and effects of private police forces be studied.

This creates serious consequences for all people, but especially affects those in society that are already disadvantaged. There is a long history of public policing being racialized or otherwise not applied equally across the population [@Alpert2006; @Tuch1997]. Communities of color have been consistently more likely to be subjected to excessive force, exacerbating inequality through social ramifications, like distrust for police and authority [@Tuch1997]. These problems exist in public police departments across the country, but often goes unaddressed, as white people are less likely to think racism in policing exists [@Tuch1997]. Yet, in many areas, white officers make up a greater proportion of the police force [@Tuch1997] and are more likely to give out tickets [@Alpert2006]. 

Typically the decision-making by police officers leading up to a stop is driven by a person appearing "different" or "out of place" [@Alpert2006]. Policing guided by these philosophies invites bias into the policing process, resulting in the targeting of males and minorities [@Alpert2006]. Policing that does not adequately address the concerns of the community, expectedly can have as detrimental effects on the community as crime can [@Daniel1970]. While crime drives down patronage of businesses, churches, and community organizations, that communities of color revolve around, ineffective policing only increases feelings of danger in the community [@Daniel1970]. Policies that emphasize transparency and accountability in policing to the community are not only comforting to residents, but result in more effective enforcement of laws.

Privatized police officers are particularly problematic when it comes to accountability, as there is a much lower legal standard for how private forces should operate. Private police forces are now under much less government scrutiny, as public police departments rely on the partnership they have with private forces [@Joh2006]. Citizens also have fewer legal protections from private police, who are not under any constitutional obligation to follow due process regulations [@Sklansky1999]. This means that private police forces are not obligated to provide Miranda warnings before interrogation, and evidence discovered by a search is almost always admissible, although the officer could be charged with assault, trespassing, or false imprisonment [@Sklansky1999]. 

Yet, despite this lack of regulation, private police officers often have the same or similar powers of public police, over that of which other citizens have [@Sklansky1999]. Additionally, private police forces formed by companies are oftentimes allowed to sit in on regional or federal task forces, giving companies access to sensitive information they did not have before [@Joh2006]. 

This creates far-reaching implications, especially in the case of university police forces, where private police patrol large areas outside of the campus. When these officers have the power to police citizens other than students, there is little to no oversight on whether this power is being exercised fairly and justly, which is antithetical to the strict limitations imposed on police in the Constitution. There will always be instances where the interests of private police are against that of the public's [@Sparrow2014]. It is important that citizens understand when these private forces are acting against the public's interests, not only to help protect themselves, but to also spread awareness for this alarming status quo, motivating law makers to more heavily regulate private police forces. 

## Literature Review

### Private Policing

Private policing is a large and growing industry, with companies spending approximately $30 billion in 2015 on private security [@Pappas2012]. The United States Department of Labor estimated that in 2018 1.15 million people in the United States were employed as Security Guards or Gaming Surveillance Officers [@USDepartmentofLabor2018]. However, it is likely for these mesaurements to be *underestimates* of the size of private policing [@Sklansky2011]. Quantitatively measuring the scope of private police is incredibly difficult, due to the secrecy and ambiguity surrounding the number of employees performing security work [@Sparrow2014; @Sklansky2011].

With private police these issues with accountability and representativeness become even more difficult to address, especially as they have become a more integral part of society. In the United States, there has been considerable growth in private policing in the last half century, sparking questions about the motivations of these private forces [@Shearing1992]. It is now common for public and private police departments to collaborate within their jurisdictions [@Shearing1992; @Sparrow2014], effectively creating a "network of public police and private security that is often overlapping, complimentary [sic] and mutually supportive" [@Bouthillier2006]. As governments have sought to cut costs, and private organizations have seen it more cost effective to hire their own workforce for protection, there has been a shift in social control out of the public sphere [@Shearing1992; @Joh2006]. 

Americans quickly became disillusioned of private policing in the early years of the mining and railroad industries. Private police forces used by the companies in these industries lead to a protection of assets over employees and went against the public interest [@Spitzer2011; @Joh2006]. This resulted in a long period where the state held a "monopoly" on policing. However, starting in the 1960's private policing began to expand, partly in response to a RAND report that re-framed private policing as "an 'industry' providing a 'service'" [@Shearing1992; @Joh2006].

Supporters of this expansion of private police forces claimed that public police had not been provided enough resources to adequately patrol their jurisdictions, creating this "vacuum" which private police were filling. This was framed as a win for everyone, as private police were now performing a role which taxpayers needed but also did not have to fund, and regulations would limit their power [@Shearing1992; @Joh2006]. Critics were concerned that now companies could give employees "state authority", and that this cooperation between governments and corporations would only protect the interests of the elite [@Shearing1992]. 

In recent history, private policing within corporations has shifted to focus on investigative labor [@Spitzer2011]. This shift represents a growing emphasis on obtaining "restitution" versus "revenge" [@Spitzer2011]. Thorough investigations allow for a better likelihood of restitution through legal means, while minimizing the risk of valuable information becoming public [@Spitzer2011]. However, any company's goal is to maximize profits, which means occasionally relying on public police, as that incurs no costs to the company [@Spitzer2011].


### Campus Policing

Campus are a unique case of private policing that is often ignored. In some ways, campus police can better serve the public's interests than public police departments. While campus police work to maintain a "good image" of the school by enforcing campus rules for students [@Jacobsen2015], they can still benefit the public, sometimes more effectively than municipal police departments. Overall, campus police feel their job is to keep students safe and make them feel comfortable [@Williams2016]. Police officers employed by universities must undergo Title IX training as all university employees must, and often complete more training about sexual harassment than their municipal counterparts [@Smith2016]. Officers with specialized training pertaining to sexual crimes typically scored lower on scales of rape myth acceptance [@Smith2016]. Perhaps a testament to this focus on safety by campus police, students generally regard their campus as a "protected space" which is safer than other areas and feel that campus police are responsible for this safe environment [@Williams2016; @Jacobsen2015].

Campus police officers also play different roles in the lives of those within their jurisdiction. Police on campuses often must play the role of a more parental figure, as most young adults at college are growing into and adjusting to their first experiences living on their own [@Williams2016]. Students feel that campus police officers should protect them while simultaneously not interfering with their lives, such as "overreacting" to students participating in under-aged drinking [@Jacobsen2015]. This puts campus police officers in an interesting situation, where they are thought of by many students to be "not real cops", while oftentimes still having the same legal powers as public law enforcement officers [@Williams2016]. Students also delegitamize campus police by popularizing rumors that campus police are officers that could not get a job with the state or munincipal police [@Jacobsen2015] or anecdotes of excessive force [@Williams2016]. 

This lack of legitimacy of campus police in students' eyes may also stem from the history of campus police. Early campus police in the first half of the twentieth century were little more than security guards, who could investigate and detain, but only refer to the administration for punishment [@Sloan1992]. As unrest became widespread on campuses across the country in the late 1960's, college administrators faced losing control of their student populations, and a reliance on outsiders to keep peace on campus [@Sloan1992]. Colleges were also growing rapidly during this time, which was accompanied by increases in crime [@Sloan1992]. This led to the founding of official campus police departments made up of sworn law enforcers whose training, duties, and organization mirrored that of traditional urban police departments [@Sloan1992].  

However, the attitudes of university police officers greatly contrast that of students attending the university. Overwhelmingly, campus police felt that students were, in general, respectful of the rules and cooperative with officers [@Sloan1992]. Officers felt that while a minority of students created most of the trouble, outsiders posed the greatest threat to campus security [@Sloan1992]. Campus police felt a strong sense of duty towards serving the university community and enforcing campus rules [@Gelber1972]. This gives evidence that while campus police officers must police a much different population with different types of crimes than municipal police traditionally do, that they will react and operate in a similar manner. 

## Methodology

This project relies heavily on computational methods of analysis. While the City of Chicago releases downloadable data-sets of police reports for the entire city, the University of Chicago only publishes records on a university website. Therefore, the data from the UCPD on incident reports, traffic stops, and field interviews will be web-scraped into a usable data-set using the `rvest` package in R. The University of Chicago also provides arrest record information upon request. This data would allow for the study of crime patterns both inside and outside the UCPD's jurisdicion, and how each department responded to reported crimes. 

Incident reports include data on the type of incident that occurred, the reported location of the incident, the time the incident was reported, the time the incident was reported to have occurred, a description of the incident, the disposition of the incident and a case number. Traffic stop data includes the time the stop occurred, the location of the stop, the race and gender of the driver, the IDOT classification of the traffic stop, the reason for the traffic stop, any citations/violations that resulted from the stop, the disposition of the stop, and whether the officer searched the vehicle. Daily field interviews encompass any other contact that UCPD officers have with civilians, and include the time and location of the stop, who the stop was initiated by, the race and gender of the person who was stopped, the reason for the stop, the disposition of the incident, and whether a search was conducted. According to the University, arrest reports "include identifying information of the arrestee (such as name, age, address and photograph); arrest charges; time and location of the arrest; name of the investigating or arresting law enforcement agency; amount of bail or bond; and details on incarceration" [@TheUniversityofChicago2015].

Additional sources of data may be gathered to supplement the analysis, such as demographic data from the US Census API, national data-sets on crime from federal organisations like the Federal Bureau of Investigation, and non-public information like the full text of police reports from the City of Chicago through a Freedom of Information Act request or contact with the Office of the Inspector General. Additional data would primarily be used to gather data on the racial backgrounds of officers and perpetrators of crimes. Incident reports from UCPD and CPD do not formally contain information about race, age, or even gender, and would need to be inferred by the location of the incident, or gathered from a different data-source.

Unsupervised Machine Learning techniques will be used alongside an exploratory data analysis to better understand the reports that each police department handles within the jurisdiction of the UCPD. This would likely include extensive visual analyses of the data to create a breakdown of reports in the area and ascertain clusterability. Unsupervised clustering could be used to reduce the feature space of the data from each respective department, to clarify what types of crimes are happening in which locations, or to discern whether a combined data-set of all reports from both departments can be reliably separated on their attributes alone.

A variety of modeling methods would be used to predict which department (or both) responded to a specific report. This will provide more evidence for how each department uniquely responds to reports of crimes and what possible ramifications for police and citizens this could impose. The modeling algorithms used would have to be able to predict categorical outcomes, ruling out typical linear regression. A logistic model could be used to model only a binary outcome between either department. More complicated methods such as Linear or Quadratic Discriminant Analysis, Naive Bayes, K-Nearest Neighbors, Decision Trees, or Random Forests would be used and their performance compared to pick the best models to analyze. 

A formal text analysis would also be conducted to shed light on structural relationships within these reports. Using topic modeling we can attempt to understand general trends in these reports. The results of the topic models can be compared between the different corpora of texts that each organization collects. Any results from the topic models or other general text analysis methods can be used to engineer new features that can be used in the models described previously. For example, in the data-set of UCPD reports, each observation of a report not only includes a category of the reported crime, but also a textual description. While the crime might be categorized as a "theft", the description will often include what was reported missing, allowing us to create new features distinctly categorizing thefts of electronics from thefts of bikes, or an estimated value of the missing goods.

\newpage
## References
